Stock.create(name: 'Stock1', unit_price: 100, interest: 30, duration: 1)
Stock.create(name: 'Stock2', unit_price: 200, interest: 25, duration: 1)
Stock.create(name: 'Stock2', unit_price: 200, interest: 25, duration: 1)
Stock.create(name: 'Stock2', unit_price: 200, interest: 25, duration: 4)
Stock.create(name: 'Stock2', unit_price: 30, interest: 25, duration: 3)
Stock.create(name: 'Stock2', unit_price: 300, interest: 25, duration: 1)
Stock.create(name: 'Stock2', unit_price: 10, interest: 25, duration: 2)
